#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
PROJECT_DIR="$( dirname "$SCRIPT_DIR}" )";
cd $PROJECT_DIR

sort -uf -o wordlist.txt wordlist.txt
echo "Sorted wordlist.txt!"
