name: ship-package

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for Changed Files
        id: changed-files
        uses: tj-actions/changed-files@bab30c2299617f6615ec02a68b9a40d10bd21366
        with:
          files: |
            annotated_logger
            Dockerfile
            pyproject.toml
            requirements.txt

      - name: Log into registry
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PW }}

      - name: Build Package
        uses: ./ # Action defined in action.yaml in the root
        if: steps.changed-files.outputs.any_changed == 'true'
