name: package-quality-control

on:
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Checks that version number has been updated
  package-quality-control:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current PR Branch
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Check for Changed Files
        id: changed-files
        uses: tj-actions/changed-files@bab30c2299617f6615ec02a68b9a40d10bd21366
        with:
          files: |
            pyproject.toml
            annotated_logger/__init__.py
      - name: Install hatch
        if: steps.changed-files.outputs.any_changed == 'true'
        run: python -m pip install hatch
      - name: Compare Versions
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          export BRANCH_VERSION=$(hatch version)
          git checkout main
          export MAIN_VERSION=$(hatch version)

          if [[ "$BRANCH_VERSION" == "$MAIN_VERSION" ]]; then echo "Please update package version number." && exit 1; fi
