name: Pytest

on:
  pull_request:
  push:
    branches: [ main ]


jobs:
  pytest:
    permissions:
      contents: read

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # pytest-forked does not work on windows and we currently use it for isolation
        # of logging configs as logging.dictConfig has a setting to not disable old loggers
        # but, does seem to trample old handlers, filters and formatters
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "pypy3.9", "pypy3.10"]
        exclude:
          - os: macos-latest
            python-version: "3.9"
          - os: windows-latest
            python-version: "3.9"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install hatch
        hatch env create dev
    - name: Test with pytest
      run: |
        # Need relative files for the action to report, but it messes up mutmut
        echo "[run]" >> .coveragerc
        echo "relative_files = true" >> .coveragerc
        cat .coveragerc

        hatch run dev:pytest
      env:
        COVERAGE_FILE: ".coverage.${{ matrix.os }}.${{ matrix.python-version }}"
    - name: Store Pull Request comment to be posted
      uses: actions/upload-artifact@v4
      if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
      with:
        name: python-coverage-comment-action
        path: python-coverage-comment-action.txt
        include-hidden-files: true
